export const getBankCodeType = [
    { name: "000 - BANCO BANKPAR S.A.", id: "000"},
    { name: "001 - BANCO DO BRASIL S.A.", id: "001"},
    { name: "003 - BANCO DA AMAZONIA S.A.", id: "003"},
    { name: "004 - BANCO DO NORDESTE DO BRASIL S.A.", id: "004"},
    { name: "008 - Banco Santander Banespa S.A.", id: "008"},
    { name: "011 - SICOOB", id: "011"},
    { name: "012 - BANCO STANDARD DE INVESTIMENTOS S.A.", id: "012"},
    { name: "021 - BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO", id: "021"},
    { name: "024 - BANCO DE PERNAMBUCO S.A. - BANDEPE", id: "024"},
    { name: "025 - BANCO ALFA S.A.", id: "025"},
    { name: "027 - Banco do Estado de Santa Catarina S.A.", id: "027"},
    { name: "029 - BANCO BANERJ S.A.", id: "029"},
    { name: "031 - BANCO BEG S.A.", id: "031"},
    { name: "033 - BANCO SANTANDER (BRASIL) S.A.", id: "033"},
    { name: "036 - BANCO BRADESCO BBI S.A.", id: "036"},
    { name: "037 - BANCO DO ESTADO DO PARA S.A.", id: "037"},
    { name: "038 - Banco Banestado S.A.", id: "038"},
    { name: "039 - Banco do Estado do Piauí S.A. – BEP", id: "039"},
    { name: "040 - BANCO CARGILL S.A.", id: "040"},
    { name: "041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.", id: "041"},
    { name: "044 - BANCO BVA S.A.", id: "044"},
    { name: "045 - BANCO OPPORTUNITY S.A.", id: "045"},
    { name: "047 - BANCO DO ESTADO DE SERGIPE S.A.", id: "047"},
    { name: "062 - HIPERCARD BANCO MULTIPLO S.A.", id: "062"},
    { name: "063 - BANCO IBI S.A. BANCO MULTIPLO", id: "063"},
    { name: "064 - GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.", id: "064"},
    { name: "065 - BANCO BRACCE S.A.", id: "065"},
    { name: "066 - Banco Morgan Stanley Dean Witter S.A.", id: "066"},
    { name: "069 - BPN BRASIL BANCO MULTIPLO S.A.", id: "069"},
    { name: "069-8 - BPN BrasiBanco Mútiplo S.A.", id: "069-8"},
    { name: "070 - BRB - BANCO DE BRASILIA S.A.", id: "070"},
    { name: "072 - BANCO RURAL MAIS S.A.", id: "072"},
    { name: "073 - BB BANCO POPULAR DO BRASIL S.A.", id: "073"},
    { name: "073-6 - BB Banco Popular do BrasiS.A.", id: "073-6"},
    { name: "074 - BANCO J. SAFRA S.A.", id: "074"},
    { name: "075 - Banco CR2 S.A.", id: "075"},
    { name: "076 - Banco KDB S.A.", id: "076"},
    { name: "077 - Banco Inter", id: "077"},
    { name: "078 - BES INVESTIMENTO DO BRASIL S.A.-BANCO DE INVESTIMENTO", id: "078"},
    { name: "079 - BANCO ORIGINAL DO AGRONEGOCIO S.A.", id: "079"},
    { name: "084 - SISPRIME", id: "084"},
    { name: "096 - BANCO BMeF DE SERVICOS DE LIQUIDACAO E CUSTODIA S.A", id: "096"},
    { name: "099 - Unipraime Cooperativa de Credito", id: "099"},
    { name: "104 - CAIXA ECONOMICA FEDERAL", id: "104"},
    { name: "107 - BANCO BBM S.A.", id: "107"},
    { name: "112 - UNICRED BRASIL CENTRAL", id: "112"},
    { name: "116 - Banco Único S.A.", id: "116"},
    { name: "119 - BANCO WESTERN UNION DO BRASIL S.A.", id: "119"},
    { name: "133 - BANCO CRESOL", id: "133"},
    { name: "136 - CONF NAC COOP CENTRAIS UNICRED", id: "136"},
    { name: "151 - Banco Nossa Caixa S.A.", id: "151"},
    { name: "175 - Banco Finasa S.A.", id: "175"},
    { name: "184 - BANCO ITAU BBA S.A.", id: "184"},
    { name: "184-8 - Banco Itaú BBA S.A.", id: "184-8"},
    { name: "204 - BANCO BRADESCO CARTOES S.A.", id: "204"},
    { name: "208 - BANCO BTG PACTUAL S.A.", id: "208"},
    { name: "210 - Dresdner Bank Lateinamerika Aktiengesellschaft", id: "210"},
    { name: "212 - Banco Matone S.A.", id: "212"},
    { name: "213 - Banco Arbi S.A.", id: "213"},
    { name: "214 - BANCO DIBENS S.A.", id: "214"},
    { name: "215 - BANCO COMERCIAL E DE INVESTIMENTO SUDAMERIS S.A.", id: "215"},
    { name: "217 - BANCO JOHN DEERE S.A.", id: "217"},
    { name: "218 - BANCO BONSUCESSO S.A.", id: "218"},
    { name: "222 - BANCO CREDIT AGRICOLE BRASIL S.A.", id: "222"},
    { name: "224 - BANCO FIBRA S.A.", id: "224"},
    { name: "225 - BANCO BRASCAN S.A.", id: "225"},
    { name: "229 - BANCO CRUZEIRO DO SUL S.A.", id: "229"},
    { name: "230 - Unicard Banco Múltiplo S.A.", id: "230"},
    { name: "233 - BANCO CIFRA S.A.", id: "233"},
    { name: "237 - BANCO BRADESCO S.A.", id: "237"},
    { name: "241 - Banco Clássico S.A.", id: "241"},
    { name: "243 - Banco Máxima S.A.", id: "243"},
    { name: "246 - BANCO ABC BRASIL S.A.", id: "246"},
    { name: "247 - Banco UBS S.A.", id: "247"},
    { name: "248 - BANCO BOAVISTA INTERATLANTICO S.A.", id: "248"},
    { name: "249 - BANCO INVESTCRED UNIBANCO S.A.", id: "249"},
    { name: "250 - BCV - BANCO DE CREDITO E VAREJO S.A.", id: "250"},
    { name: "252 - Banco Fininvest S.A.", id: "252"},
    { name: "254 - Paraná Banco S.A.", id: "254"},
    { name: "260 - NU PAGAMENTOS S.A", id: "260"},
    { name: "263 - BANCO CACIQUE S.A.", id: "263"},
    { name: "265 - BANCO FATOR S.A.", id: "265"},
    { name: "266 - Banco Cédula S.A.", id: "266"},
    { name: "274 - Banco BMP", id: "274"},
    { name: "290 - Banco Pagseguro", id: "290"},
    { name: "300 - Banco de La Nacion Argentina", id: "300"},
    { name: "318 - BANCO BMG S.A.", id: "318"},
    { name: "320 - BANCO INDUSTRIAL E COMERCIAL S.A.", id: "320"},
    { name: "323 - MERCADO PAGO", id: "323"},
    { name: "336 - C6 S.A", id: "336"},
    { name: "341 - ITAU UNIBANCO S.A.", id: "341"},
    { name: "347 - Banco Sudameris BrasiS.A.", id: "347"},
    { name: "348 - BANCO XP S.A.", id: "348"},
    { name: "356 - BANCO REAL S.A.", id: "356"},
    { name: "366 - BANCO SOCIETE GENERALE BRASIL S.A.", id: "366"},
    { name: "370 - BANCO WESTLB DO BRASIL S.A.", id: "370"},
    { name: "376 - BANCO J. P. MORGAN S.A.", id: "376"},
    { name: "389 - BANCO MERCANTIL DO BRASIL S.A.", id: "389"},
    { name: "392 - Banco Mercantide São Paulo S.A.", id: "392"},
    { name: "394 - BANCO FINASA BMC S.A.", id: "394"},
    { name: "399 - HSBC BANK BRASIL S.A. - BANCO MULTIPLO", id: "399"},
    { name: "403 - Banco Cora", id: "403"},
    { name: "409 - UNIBANCO - UNIAO DE BANCOS BRASILEIROS S.A.", id: "409"},
    { name: "412 - Banco CapitaS.A.", id: "412"},
    { name: "422 - BANCO SAFRA S.A.", id: "422"},
    { name: "453 - BANCO RURAL S.A.", id: "453"},
    { name: "456 - BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S.A.", id: "456"},
    { name: "464 - BANCO SUMITOMO MITSUI BRASILEIRO S.A.", id: "464"},
    { name: "473 - BANCO CAIXA GERAL - BRASIL S.A.", id: "473"},
    { name: "477 - CITIBANK S.A.", id: "477"},
    { name: "479 - BANCO ITAUBANK S.A", id: "479"},
    { name: "487 - DEUTSCHE BANK S.A. - BANCO ALEMAO", id: "487"},
    { name: "488 - JPMORGAN CHASE BANK", id: "488"},
    { name: "492 - ING BANK N.V.", id: "492"},
    { name: "494 - Banco de La Republica OrientadeUruguay", id: "494"},
    { name: "495 - Banco de La Provincia de Buenos Aires", id: "495"},
    { name: "505 - BANCO CREDIT SUISSE (BRASIL) S.A.", id: "505"},
    { name: "536 - NEON PAGAMENTOS", id: "536"},
    { name: "579 - Banco Atlas", id: "579"},
    { name: "600 - BANCO LUSO BRASILEIRO S.A.", id: "600"},
    { name: "604 - BANCO INDUSTRIAL DO BRASIL S.A.", id: "604"},
    { name: "610 - BANCO VR S.A.", id: "610"},
    { name: "611 - BANCO PAULISTA S.A.", id: "611"},
    { name: "612 - BANCO GUANABARA S.A.", id: "612"},
    { name: "613 - Banco Pecúnia S.A.", id: "613"},
    { name: "623 - BANCO PANAMERICANO S.A.", id: "623"},
    { name: "626 - BANCO FICSA S.A.", id: "626"},
    { name: "630 - Banco Intercap S.A.", id: "630"},
    { name: "633 - BANCO RENDIMENTO S.A.", id: "633"},
    { name: "634 - BANCO TRIANGULO S.A.", id: "634"},
    { name: "637 - BANCO SOFISA S.A.", id: "637"},
    { name: "638 - BANCO PROSPER S.A.", id: "638"},
    { name: "641 - BANCO ALVORADA S.A.", id: "641"},
    { name: "643 - BANCO PINE S.A.", id: "643"},
    { name: "652 - ITAU UNIBANCO HOLDING S.A.", id: "652"},
    { name: "653 - BANCO INDUSVAL S.A.", id: "653"},
    { name: "654 - Banco A.J.Renner S.A.", id: "654"},
    { name: "655 - BANCO VOTORANTIM S.A.", id: "655"},
    { name: "707 - BANCO DAYCOVAL S.A.", id: "707"},
    { name: "719 - BANIF-BANCO INTERNACIONAL DO FUNCHAL (BRASIL)S.A.", id: "719"},
    { name: "721 - Banco CredibeS.A.", id: "721"},
    { name: "724 - Banco Porto Seguro S.A.", id: "724"},
    { name: "734 - Banco Gerdau S.A.", id: "734"},
    { name: "735 - Banco PottenciaS.A.", id: "735"},
    { name: "738 - Banco Morada S.A.", id: "738"},
    { name: "739 - BANCO BGN S.A.", id: "739"},
    { name: "740 - BANCO BARCLAYS S.A.", id: "740"},
    { name: "741 - Banco Ribeirão Preto S.A.", id: "741"},
    { name: "743 - Banco Semear S.A.", id: "743"},
    { name: "744 - BankBoston N.A.", id: "744"},
    { name: "745 - BANCO CITIBANK S.A.", id: "745"},
    { name: "746 - BANCO MODAL S.A.", id: "746"},
    { name: "747 - BANCO RABOBANK INTERNATIONAL BRASIL S.A.", id: "747"},
    { name: "748 - BANCO COOPERATIVO SICREDI S.A.", id: "748"},
    { name: "749 - BANCO SIMPLES S.A.", id: "749"},
    { name: "751 - SCOTIABANK BRASIL S.A. BANCO MULTIPLO", id: "751"},
    { name: "752 - BANCO BNP PARIBAS BRASIL S.A.", id: "752"},
    { name: "753 - Banco ComerciaUruguai S.A.", id: "753"},
    { name: "755 - BANK OF AMERICA MERRILL LYNCH BANCO MULTIPLO S.A.", id: "755"},
    { name: "756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB", id: "756"},
    { name: "757 - Banco KEB do BrasiS.A.", id: "757"},
    { name: "758 - My Mabu Incorp Py - Recebimentos", id: "758"},
    { name: "A005 - The Royal Bank of Scotland N.V.", id: "A005"},
    { name: "A007 - Banco de Galicia 14​ y Buenos Aires S.A.", id: "A007"},
    { name: "A011 - Banco de la Nación Argentina", id: "A011"},
    { name: "A014 - Banco de la Provincia de Buenos Aires", id: "A014"},
    { name: "A015 - Industrial and Commercial Bank of China S.A.", id: "A015"},
    { name: "A016 - Citibank N.A.", id: "A016"},
    { name: "A017 - BBvA Banco Francés S.A.", id: "A017"},
    { name: "A018 - The Bank of Tokyo-Mitsubishi UFJ, LTD.", id: "A018"},
    { name: "A020 - Banco de la Provincia de Córdoba S.A.", id: "A020"},
    { name: "A027 - Banco Supervielle S.A.", id: "A027"},
    { name: "A029 - Banco de la Ciudad de Buenos Aires", id: "A029"},
    { name: "A030 - Central de la República Argentina", id: "A030"},
    { name: "A034 - Banco Patagonia S.A.", id: "A034"},
    { name: "A044 - Banco Hipotecario S.A.", id: "A044"},
    { name: "A045 - Banco de San Juan S.A.", id: "A045"},
    { name: "A046 - Banco do Brasil S.A. Argentina", id: "A046"},
    { name: "A060 - Banco de Tucumán S.A.", id: "A060"},
    { name: "A065 - Banco Municipal de Rosario", id: "A065"},
    { name: "A072 - Banco Santander Río S.A.", id: "A072"},
    { name: "A083 - Banco del Chubut S.A.", id: "A083"},
    { name: "A086 - Banco de Santa Cruz S.A.", id: "A086"},
    { name: "A093 - Banco de la Pampa Sociedad de Economía Mixta", id: "A093"},
    { name: "A094 - Banco de Corrientes S.A.", id: "A094"},
    { name: "A097 - Banco Provincia del Neuquén S.A.", id: "A097"},
    { name: "A143 - Brubank S.A.U.", id: "A143"},
    { name: "A147 - Banco Interfinanzas S.A.", id: "A147"},
    { name: "A150 - HSBC Bank Argentina S.A.", id: "A150"},
    { name: "A165 - JP Morgan Chase Bank NA (Sucursal Buenos Aires)", id: "A165"},
    { name: "A191 - Banco Credicoop Cooperativo Limitado", id: "A191"},
    { name: "A198 - Banco de Valores S.A.", id: "A198"},
    { name: "A247 - Banco Roela S.A.", id: "A247"},
    { name: "A254 - Banco Mariva S.A.ī", id: "A254"},
    { name: "A259 - Banco Itaú Argentina S.A.", id: "A259"},
    { name: "A262 - Bank of America National Association", id: "A262"},
    { name: "A266 - BNP Paribas", id: "A266"},
    { name: "A268 - Banco Provincia de Tierra del Fuego", id: "A268"},
    { name: "A269 - Banco de la República Oriental del Uruguay", id: "A269"},
    { name: "A277 - Banco Sáenz S.A.", id: "A277"},
    { name: "A281 - Banco Meridian S.A.", id: "A281"},
    { name: "A285 - Banco Macro S.A.", id: "A285"},
    { name: "A295 - American Express Bank LTD. S.A.", id: "A295"},
    { name: "A299 - Banco Comafi S.A.", id: "A299"},
    { name: "A300 - Banco de Inversión y Comercio Exterior S.A.", id: "A300"},
    { name: "A301 - Banco Piano S.A.", id: "A301"},
    { name: "A305 - Banco Julio S.A.", id: "A305"},
    { name: "A309 - Nuevo Banco de la Rioja S.A.", id: "A309"},
    { name: "A310 - Banco del Sol S.A.", id: "A310"},
    { name: "A311 - Nuevo Banco del Chaco S.A.", id: "A311"},
    { name: "A312 - MBA Lazard Banco de Inversiones S.A.", id: "A312"},
    { name: "A315 - Banco de Formosa S.A.", id: "A315"},
    { name: "A319 - Banco CMF S.A.", id: "A319"},
    { name: "A321 - Banco de Santiago del Estero S.A.", id: "A321"},
    { name: "A322 - Banco Industrial S.A.", id: "A322"},
    { name: "A325 - Deutsche Bank S.A.", id: "A325"},
    { name: "A330 - Nuevo Banco de Santa Fe S.A.", id: "A330"},
    { name: "A331 - Banco Cetelem Argentina S.A.", id: "A331"},
    { name: "A332 - Banco de Servicios Financieros S.A.", id: "A332"},
    { name: "A336 - Banco Bradesco Argentina S.A.", id: "A336"},
    { name: "A338 - Banco de Servicios y Transacciones S.A.", id: "A338"},
    { name: "A339 - RCI Banque S.A.", id: "A339"},
    { name: "A340 - BACS Banco de Crédito y Securitización S.A.", id: "A340"},
    { name: "A341 - Más Ventas S.A.", id: "A341"},
    { name: "A384 - Wilobank S.A.", id: "A384"},
    { name: "A386 - Nuevo Banco de Entre Ríos S.A.", id: "A386"},
    { name: "A389 - Banco Columbia S.A.", id: "A389"},
    { name: "A405 - Ford Credit Compañía Financiera S.A.", id: "A405"},
    { name: "A406 - Metrópolis Compañía Financiera S.A.", id: "A406"},
    { name: "A408 - Compañía Financiera Argentina S.A.", id: "A408"},
    { name: "A413 - Montemar Compañía Financiera S.A.", id: "A413"},
    { name: "A415 - Transatlántica Compañía Financiera S.A.", id: "A415"},
    { name: "A428 - Caja de Crédito Coop. La Capital del Plata LTDA.", id: "A428"},
    { name: "A431 - Banco Coinag S.A.", id: "A431"},
    { name: "A432 - Banco de Comercio S.A.", id: "A432"},
    { name: "A434 - Caja de Crédito Cuenca Coop. LTDA.", id: "A434"},
    { name: "A437 - Volkswagen Credit Compañía Financiera S.A.", id: "A437"},
    { name: "A438 - Cordial Compañía Financiera S.A.", id: "A438"},
    { name: "A440 - Fiat Crédito Compañía Financiera S.A.", id: "A440"},
    { name: "A441 - GPAT Compañía Financiera S.A.", id: "A441"},
    { name: "A442 - Mercedes-Benz Compañía Financiera Argentina S.A.", id: "A442"},
    { name: "A443 - Rombo Compañía Financiera S.A.", id: "A443"},
    { name: "A444 - John Deere Credit Compañía Financiera S.A.", id: "A444"},
    { name: "A445 - PSA Finance Argentina Compañía Financiera S.A.", id: "A445"},
    { name: "A446 - Toyota Compañía Financiera de Argentina S.A.", id: "A446"},
    { name: "A448 - Finandino Compañía Financiera S.A.", id: "A448"},
    { name: "A992 - Provincanje S.A.", id: "A992"},
    { name: "BF - Banco Familiar", id: "BF"},
    { name: "M03 - BANCO FIAT S.A.", id: "M03"},
    { name: "M06 - BANCO DE LAGE LANDEN BRASIL S.A.", id: "M06"},
    { name: "M07 - BANCO GMAC S.A.", id: "M07"},
    { name: "M08 - BANCO CITICARD S.A.", id: "M08"},
    { name: "M09 - BANCO ITAUCRED FINANCIAMENTOS S.A.", id: "M09"},
    { name: "M11 - BANCO IBM S.A.", id: "M11"},
    { name: "M14 - BANCO VOLKSWAGEN S.A.", id: "M14"},
    { name: "M16 - BANCO RODOBENS S.A.", id: "M16"},
    { name: "M18 - BANCO FORD S.A.", id: "M18"},
    { name: "M19 - BANCO CNH CAPITAL S.A.", id: "M19"},
    { name: "M20 - BANCO TOYOTA DO BRASIL S.A.", id: "M20"},
    { name: "M22 - BANCO HONDA S.A.", id: "M22"},
    { name: "M23 - BANCO VOLVO (BRASIL) S.A.", id: "M23"},
  ];
  